# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "生成 Framework ，并引用对应的 Framework"
  lane :pod_generate_frameworks do |options|
    ENV['PODFILE_TYPE'] = 'generate_frameworks'
    ENV["BUILD_PODS"] = options[:build]
    ENV["FRAMEWORK_PODS"] = ''
    cocoapods
    ENV['PODFILE_TYPE'] = ''
    ENV["BUILD_PODS"] = ''
    ENV["FRAMEWORK_PODS"] = options[:build]
    if !(ENV["FRAMEWORK_PODS"] && ENV["FRAMEWORK_PODS"].length > 0) # 如果 build 为空，说明是 build all ，设置成 development
      ENV['PODFILE_TYPE'] = 'development'
    end
    cocoapods
  end

  desc "直接引用 Framework"
  lane :pod_frameworks do |options|
    ENV['PODFILE_TYPE'] = ''
    ENV["FRAMEWORK_PODS"] = options[:frameworks]
    if !(options[:frameworks] && options[:frameworks] != 'all')
      ENV['PODFILE_TYPE'] = 'development'
    end
    cocoapods
  end

  desc "全部使用源码"
  lane :pod_source do |options|
    ENV['PODFILE_TYPE'] = ''
    ENV["FRAMEWORK_PODS"] = ''
    cocoapods
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
